---
- name: "Download Kibana's deb"
  get_url:
    url: "{{ kibana_deb_url }}"
    dest: "files/kibana-{{ kibana_version }}-amd64.deb"
    validate_certs: false
  delegate_to: localhost
  register: download_kibana
  until: download_kibana is succeeded
  when: kibana_install_type == 'remote'
- name: Copy Kibana to manage host
  copy:
    src: "files/kibana-{{ kibana_version }}-amd64.deb"
    mode: 0755
    dest: "/tmp/kibana-{{ kibana_version }}-amd64.deb"
