---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    groups:
      - kibana
    image: docker.io/pycontribs/centos:7
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
  - name: centos8
    groups:
      - kibana
    image: docker.io/pycontribs/centos:8
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
  - name: ubuntu
    groups:
      - kibana
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
