---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    groups:
      - kibana
    image: docker.io/pycontribs/centos:7
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy